#!/usr/bin/env python3

import sys
import os
import argparse
import re
import gzip

# 预编译正则，用于快速提取 non-variant block 的 END
END_RE = re.compile(r"END=(\d+)")

# 允许的杂合基因型（含 phased）
HET_GTS = {"0/1", "1/0", "0|1", "1|0"}


def is_snp(ref, alt):
    """
    判断是否为 SNP：
    REF 为单碱基，ALT 中至少包含一个 A/C/G/T
    """
    if len(ref) != 1:
        return False

    alts = alt.split(",")
    if len(alts) > 2:
        return False
    for a in alts:
        if len(a) == 1 and a in "ACGT":
            return True
    return False


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Compute heterozygous SNP count, total non-variant block length, "
            "and their ratio from a single-sample GATK gVCF file (gzip-compressed). "
            "Only GT=0/1, 1/0, 0|1, or 1|0 (FORMAT first field) "
            "is counted as heterozygous."
        )
    )
    parser.add_argument(
        "gvcf",
        help="Input gVCF file generated by GATK (gzip-compressed, .g.vcf.gz)"
    )

    args = parser.parse_args()

    sample_name = os.path.basename(args.gvcf)

    het_snp_count = 0
    non_variant_length = 0

    # gzip 以文本模式读取
    with gzip.open(args.gvcf, "rt") as f:
        for line in f:
            if line.startswith("#"):
                continue

            fields = line.rstrip().split("\t")

            # 基本字段
            pos = int(fields[1])
            ref = fields[3]
            alt = fields[4]
            info = fields[7]

            # non-variant block
            if alt == "<NON_REF>":
                m = END_RE.search(info)
                if m:
                    end = int(m.group(1))
                    non_variant_length += end - pos + 1
                continue

            # 非 SNP 位点跳过
            if not is_snp(ref, alt):
                continue

            # FORMAT 假定 GT 在第一位
            if len(fields) < 10:
                continue

            gt = fields[9].split(":", 1)[0]

            if gt in HET_GTS:
                het_snp_count += 1

    ratio = het_snp_count / non_variant_length if non_variant_length > 0 else 0

    # 输出
    print("Sample\tHet_SNP_count\tNon_variant_length\tHetSNP_to_block_ratio")
    print(f"{sample_name}\t{het_snp_count}\t{non_variant_length}\t{ratio:.6e}")


if __name__ == "__main__":
    main()
