# -*- coding: utf-8 -*-
"""
Created on 2022 10-14

@author: Yudongcai

@Email: yudong_cai@163.com
"""
import typer
import pandas as pd
from collections import Counter

def main(siteinfo: str = typer.Argument(..., help="siteinfo file generated by 01_vcf_to_estsfs.py"),
         pvalues: str = typer.Argument(..., help="anc_p file generated by est-sfs"),
         datafile: str = typer.Argument(..., help="datafile generated by 01_vcf_to_estsfs.py"),
         outprefix: str = typer.Argument(..., help="output file prefix")):
    df1 = pd.read_csv(siteinfo, sep='\t')
    
    df2 = pd.read_csv(pvalues, sep='\s+', skiprows=8,
                  usecols=[0, 2], header=None, names=['index', 'p_anc'])
    df2['index'] -= 1
    df2.set_index('index', inplace=True)
    
    count2allele = {'0,0,0,0': 'N',
                    '1,0,0,0': 'A',
                    '0,1,0,0': 'C',
                    '0,0,1,0': 'G',
                    '0,0,0,1': 'T'}
    df3 = pd.read_csv(datafile, sep='\t', header=None,
                      usecols=[1,2,3], names=['outgroup1', 'outgroup2', 'outgroup3'])
    for col in ('outgroup1', 'outgroup2', 'outgroup3'):
        df3[col] = df3[col].map(count2allele)
    df3['out_most_common'] = df3[['outgroup1', 'outgroup2', 'outgroup3']].apply(lambda x: Counter(x).most_common()[0][0], axis=1)
    
    mdf = pd.concat([df1[['CHROM', 'POS', 'majorAllele', 'minorAllele']], 
                     df2, 
                     df3[['out_most_common']]], axis=1)
    
    # P>=0.8用major，<=0.2用minor，0.2～0.8用外群中出现最多的。
    mdf['anc_allele'] = mdf['majorAllele']
    selection = mdf['p_anc']<=0.2
    mdf.loc[selection, 'anc_allele'] = mdf.loc[selection, 'minorAllele']
    selection = (mdf['p_anc']>0.2)&(mdf['p_anc']<0.8)
    mdf.loc[selection, 'anc_allele'] = mdf.loc[selection, 'out_most_common']
    
    mdf[['CHROM', 'POS', 'anc_allele']].to_csv(f'{outprefix}_anc.tsv.gz', sep='\t', index=False, header=False)

if __name__ == '__main__':
    typer.run(main)